### PR TITLE
Added viewer

### PR DESCRIPTION
**Pull request by arcashka**

### CODE REVIEW

**Comment by arcashka** [comment]
Opengl 4.x needed
cube will show up after diffuse, normal and displacement map loaded

**Comment by Theverat** [comment]
merged manually, moved to new branch 3d_preview.

**Comment by Theverat** [comment]
Hi,

I merged your commits and moved them to a new branch "3d_preview".

I also added you as a collaborator so you can directly work with my 
repository. (So you don't have to send pull requests and keep your fork 
in sync)
Here's the invite link: 
https://github.com/Theverat/NormalmapGenerator/invitations

The viewer works very good here, I already have a few ideas how to 
improve it (usability-wise).
I'll open a ticket on github so we can discuss them there.

regards
Simon

**Comment by Theverat** [comment]
I opened the feature issue, we can discuss ideas there: 
https://github.com/Theverat/NormalmapGenerator/issues/23

**Pull request closed without merging**
